---
title: ReciMe ER Diagram
---
erDiagram
    User ||..o{ Recipe :posts
    User ||..o{ Recipe :likes
    User ||..o{ Comment :writes
    User ||..o{ Comment :likes
    Recipe ||..o{ Comment :has
    Recipe ||..o| Vegan :ISA
    Recipe ||..o| Vegeterian :ISA
    Recipe ||..o| "Spicy / Hot" :ISA    
    Recipe ||..o| "Quick Meal" :ISA    
